---
variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - 'mvn install:install-file -Dfile=./lib/plugin.jar -DgroupId=com.sun.jdk -DartifactId=plugin -Dpackaging=jar -Dversion=0.0.1'
    - 'mvn $MAVEN_CLI_OPTS clean install -DskipTests'
  image: maven:3.6.0-jdk-8

deploy:release:
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS -DskipTests -pl runelite-client deploy --settings settings.xml'
  only:
    - master
  image: maven:3.6.0-jdk-8

deploy:preview:
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS -DskipTests -pl runelite-client deploy --settings settings.xml -DaltDeploymentRepository=s3.artifacts.client::default::s3://zenyte-runelite/preview'
  only:
    - develop
  image: maven:3.6.0-jdk-8